sonar.projectKey=mi_proyecto
sonar.projectName=Mi Proyecto
sonar.projectVersion=1.0

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
sonar.token = sqa_daee41845a8d83be4a4fce1654deccdc19e19c55
